when:
  event: tag

steps:

  linux-build:
    when:
      platform: linux
    image: debian:stable
    environment:
      VERSION: ${CI_COMMIT_TAG}
    commands:
      - apt update
      - apt install -y git build-essential curl xz-utils
      - curl -fsSL https://xmake.io/shget.text | bash
      - export PATH=$PATH:/root/.xmake
      - xmake --version
      - xmake f -m release
      - xmake
      - mkdir -p dist/linux
      - cp build/linux/x64/release/Fig dist/linux/
      - cp -r src/Module/Library dist/linux/Library
      - cd dist
      - tar -czf Fig-${VERSION}-linux.tar.gz linux

  windows-build:
    when:
      platform: windows
    environment:
      VERSION: ${CI_COMMIT_TAG}
    commands:
      - choco install -y git
      - choco install -y xmake
      - refreshenv
      - xmake f -m release
      - xmake
      - mkdir dist
      - mkdir dist/windows
      - copy build\windows\x64\release\Fig.exe dist\windows\
      - xcopy src\Module\Library dist\windows\Library /E /I
      - powershell Compress-Archive dist/windows Fig-%VERSION%-windows.zip
