name: Release Build
on:
  push:
    tags: ['*']
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: Checkout
        run: |
          apt-get update && apt-get install -y git curl
          git clone https://git.fig-lang.cn/${{ github.repository }} .
          git checkout ${{ github.ref }}
          
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y curl wget gcc g++ make build-essential
          
      - name: Install xmake
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Get Version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Build
        run: |
          xmake f -p linux -a x86_64 -m release
          xmake -j$(nproc)
          
      - name: Package
        run: |
          apt-get install -y zip
          mkdir -p Fig-${{ env.VERSION }}-linux-x86_64
          cp build/linux/x86_64/release/Fig Fig-${{ env.VERSION }}-linux-x86_64/
          cp -r src/Module/Library Fig-${{ env.VERSION }}-linux-x86_64/
          tar -czf Fig-${{ env.VERSION }}-linux-x86_64.tar.gz Fig-${{ env.VERSION }}-linux-x86_64
          sha256sum Fig-${{ env.VERSION }}-linux-x86_64.tar.gz > Fig-${{ env.VERSION }}-linux-x86_64.sha256
          
      - name: Upload to Release
        env:
          TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          apt-get install -y curl
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\":\"${{ env.VERSION }}\",\"name\":\"Fig ${{ env.VERSION }}\"}" \
            https://git.fig-lang.cn/api/v1/repos/${{ github.repository }}/releases || true
          
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @Fig-${{ env.VERSION }}-linux-x86_64.tar.gz \
            "https://git.fig-lang.cn/api/v1/repos/${{ github.repository }}/releases/${{ env.VERSION }}/assets?name=Fig-${{ env.VERSION }}-linux-x86_64.tar.gz"
            
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: text/plain" \
            --data-binary @Fig-${{ env.VERSION }}-linux-x86_64.sha256 \
            "https://git.fig-lang.cn/api/v1/repos/${{ github.repository }}/releases/${{ env.VERSION }}/assets?name=Fig-${{ env.VERSION }}-linux-x86_64.sha256"