name: Release Build
on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: Checkout
        run: |
          git clone https://git.fig-lang.cn/${{ github.repository }} .
          git checkout ${{ github.sha }}
          
      - name: Get Version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Install xmake
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Build
        run: |
          xmake f -p linux -a x86_64 -m release
          xmake -j$(nproc)
          
      - name: Package
        run: |
          mkdir -p Fig-${{ env.VERSION }}-linux-x86_64
          cp build/linux/x86_64/release/Fig Fig-${{ env.VERSION }}-linux-x86_64/
          cp -r src/Module/Library Fig-${{ env.VERSION }}-linux-x86_64/
          tar -czf Fig-${{ env.VERSION }}-linux-x86_64.tar.gz Fig-${{ env.VERSION }}-linux-x86_64
          sha256sum Fig-${{ env.VERSION }}-linux-x86_64.tar.gz > checksum.txt
          
      - name: Upload to Release
        env:
          TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          # 创建 Release
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\":\"${{ env.VERSION }}\",\"name\":\"Fig ${{ env.VERSION }}\"}" \
            https://git.fig-lang.cn/api/v1/repos/${{ github.repository }}/releases || true
          
          # 上传文件
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @Fig-${{ env.VERSION }}-linux-x86_64.tar.gz \
            "https://git.fig-lang.cn/api/v1/repos/${{ github.repository }}/releases/${{ env.VERSION }}/assets?name=Fig-${{ env.VERSION }}-linux-x86_64.tar.gz"
            
          # 上传校验和
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: text/plain" \
            --data-binary @checksum.txt \
            "https://git.fig-lang.cn/api/v1/repos/${{ github.repository }}/releases/${{ env.VERSION }}/assets?name=Fig-${{ env.VERSION }}-linux-x86_64.sha256"